# Generated by Django 5.0.14 on 2025-11-21 03:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_valoracion_cita_and_more'),
        ('scheduling', '0002_valoracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cancelado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='confirmada_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cita',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cita',
            name='reprogramado_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cita',
            name='ultima_reprogramacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada_cliente', 'Cancelada por Cliente'), ('cancelada_admin', 'Cancelada por Admin'), ('no_show', 'No Show')], db_index=True, default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_hora',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_hora'], name='scheduling__fecha_h_9b1400_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['barbero', 'fecha_hora'], name='scheduling__barbero_2edeec_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['cliente', 'fecha_hora'], name='scheduling__cliente_46c27b_idx'),
        ),
    ]
