# Generated by Django 5.0.14 on 2025-11-21 04:19

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_cita_cancelado_en_cita_confirmada_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valoracion',
            options={'ordering': ['-creada_en']},
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('cita', 'cliente')},
        ),
        migrations.AddField(
            model_name='valoracion',
            name='creada_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterModelTable(
            name='valoracion',
            table='scheduling_valoracion',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='fecha',
        ),
    ]
