# Generated by Django 5.0.14 on 2025-11-21 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_valoracion_cita_and_more'),
        ('scheduling', '0004_alter_valoracion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dia', models.DateField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('notificado_en', models.DateTimeField(blank=True, null=True)),
                ('expiracion_notificacion', models.DateTimeField(blank=True, null=True)),
                ('utilizado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='core.barbero')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='core.servicio')),
            ],
            options={
                'db_table': 'scheduling_waitlist',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['barbero', 'fecha_dia', 'activo'], name='scheduling__barbero_d62f9e_idx')],
            },
        ),
    ]
