# Generated by Django 5.0.14 on 2025-11-22 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_valoracion_cita_and_more'),
        ('scheduling', '0005_waitlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='descuento_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(help_text='Código que ingresa el cliente', max_length=50, unique=True)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto Fijo')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Porcentaje o monto fijo', max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('usos_maximos', models.IntegerField(default=0, help_text='0 = ilimitado')),
                ('usos_actuales', models.IntegerField(default=0)),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('solo_nuevos_clientes', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='core.barberia')),
                ('servicios', models.ManyToManyField(blank=True, help_text='Vacío = todos', to='core.servicio')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'db_table': 'bf_promociones',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='scheduling.promocion'),
        ),
    ]
