# Generated by Django 5.0.14 on 2025-11-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_cita_descuento_aplicado_promocion_cita_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='recordatorio_24h_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
