# Generated by Django 5.0.14 on 2025-11-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0007_cita_recordatorio_24h_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
