# Generated by Django 5.0.14 on 2025-11-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_cita_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='nota_interna',
            field=models.TextField(blank=True, null=True),
        ),
    ]
