# Generated by Django 5.0.14 on 2025-11-19 04:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('trial', 'Trial (7 días gratis)'), ('basico', 'Básico'), ('profesional', 'Profesional'), ('empresarial', 'Empresarial')], max_length=50, unique=True, verbose_name='Nombre del plan')),
                ('periodicidad', models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=10, verbose_name='Periodicidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('max_barberos', models.PositiveIntegerField(default=1, verbose_name='Máximo de barberos')),
                ('max_sucursales', models.PositiveIntegerField(default=1, verbose_name='Máximo de sucursales')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plan de licencia',
                'verbose_name_plural': 'Planes de licencia',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Superadmin (Licencias)'), ('admin_barberia', 'Admin Barberia'), ('barbero', 'Barbero'), ('cliente', 'Cliente')], db_index=True, default='cliente', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='HorarioDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.barbero')),
            ],
            options={
                'verbose_name': 'Horario de disponibilidad',
                'verbose_name_plural': 'Horarios de disponibilidad',
                'ordering': ['barbero', 'dia_semana', 'hora_inicio'],
                'unique_together': {('barbero', 'dia_semana', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='LogActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear_barberia', 'Crear Barbería'), ('suspender_barberia', 'Suspender Barbería'), ('cambiar_plan', 'Cambiar Plan'), ('pago_exitoso', 'Pago Exitoso'), ('pago_fallido', 'Pago Fallido'), ('login', 'Login'), ('error_sistema', 'Error del Sistema')], max_length=30, verbose_name='Acción')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha/Hora')),
                ('nosotros', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.nosotros')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de actividad',
                'verbose_name_plural': 'Logs de actividad',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Licencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_expiracion', models.DateField(verbose_name='Fecha de expiración')),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('pago_pendiente', models.BooleanField(default=False, verbose_name='Pago pendiente')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, verbose_name='Stripe Subscription ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nosotros', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='licencia', to='core.nosotros')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('descuento_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Descuento (%)')),
                ('codigo', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código promocional')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('clientes', models.ManyToManyField(blank=True, related_name='promociones_recibidas', to='core.cliente')),
                ('nosotros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='core.nosotros')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('duracion_minutos', models.PositiveIntegerField(default=30, verbose_name='Duración (min)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nosotros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.nosotros')),
            ],
            options={
                'verbose_name': 'Sevicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la cita')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada_cliente', 'Cancelada por Cliente'), ('cancelada_admin', 'Cancelada por Admin'), ('no_asistio', 'No Asistió')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas_cliente', models.TextField(blank=True, verbose_name='Notas del cliente')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas internas (admin)')),
                ('confirmada_email', models.BooleanField(default=False, verbose_name='Email de confirmación enviado')),
                ('recordatorio_enviado', models.BooleanField(default=False, verbose_name='Recordatorio enviado')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('cancelado_en', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('barbero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.barbero')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.cliente')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicio')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha', '-hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Puntuación (1-5 estrellas)')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentario')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='valoracion', to='core.cita')),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-creado'],
            },
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha', 'barbero'], name='core_cita_fecha_005458_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['cliente', 'fecha'], name='core_cita_cliente_eabebe_idx'),
        ),
    ]
