# Generated by Django 5.0.14 on 2025-11-20 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plan_alter_user_rol_horariodisponibilidad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre'], 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='nosotros',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='nosotros',
        ),
        migrations.CreateModel(
            name='Barberia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la barbería')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('nosotros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barberias', to='core.nosotros')),
            ],
            options={
                'verbose_name': 'Barbería',
                'verbose_name_plural': 'Barberías',
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='barberia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.barberia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='barberia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='core.barberia'),
            preserve_default=False,
        ),
    ]
