# Generated by Django 5.0.14 on 2025-11-21 03:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_servicio_options_remove_servicio_nosotros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='cita',
        ),
        migrations.AlterModelOptions(
            name='horariodisponibilidad',
            options={'ordering': ['barbero', 'dia_semana', 'hora_inicio']},
        ),
        migrations.AlterModelOptions(
            name='licencia',
            options={},
        ),
        migrations.AlterModelOptions(
            name='logactividad',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='promocion',
            options={'ordering': ['-fecha_inicio']},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['nombre']},
        ),
        migrations.RenameField(
            model_name='invitacionbarbero',
            old_name='creado',
            new_name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='invitacionbarbero',
            name='expira',
        ),
        migrations.AddField(
            model_name='invitacionbarbero',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barberia',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='barberia',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='barbero',
            name='nosotros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barberos', to='core.nosotros'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='acepta_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='acepta_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono 7–15 dígitos (opcional +).', regex='^\\+?[0-9]{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='horariodisponibilidad',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='horariodisponibilidad',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
        migrations.AlterField(
            model_name='horariodisponibilidad',
            name='hora_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horariodisponibilidad',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='invitacionbarbero',
            name='nosotros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='core.nosotros'),
        ),
        migrations.AlterField(
            model_name='invitacionbarbero',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='core.sucursal'),
        ),
        migrations.AlterField(
            model_name='invitacionbarbero',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='fecha_expiracion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='pago_pendiente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='licencia',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='accion',
            field=models.CharField(choices=[('crear_barberia', 'Crear Barbería'), ('suspender_barberia', 'Suspender Barbería'), ('cambiar_plan', 'Cambiar Plan'), ('pago_exitoso', 'Pago Exitoso'), ('pago_fallido', 'Pago Fallido'), ('login', 'Login'), ('error_sistema', 'Error Sistema')], max_length=30),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_barberos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_sucursales',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(choices=[('trial', 'Trial'), ('basico', 'Básico'), ('profesional', 'Profesional'), ('empresarial', 'Empresarial')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='periodicidad',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('anual', 'Anual')], default='mensual', max_length=10),
        ),
        migrations.AlterField(
            model_name='plan',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descuento_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin_barberia', 'Admin Barbería'), ('barbero', 'Barbero'), ('cliente', 'Cliente')], db_index=True, default='cliente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='Valoracion',
        ),
    ]
