# Generated by Django 5.0.14 on 2025-11-22 05:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_valoracion_cita_and_more'),
        ('scheduling', '0006_cita_descuento_aplicado_promocion_cita_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puntos_fidelidad',
            field=models.JSONField(blank=True, default=dict, help_text="{'barberia_id': puntos}"),
        ),
        migrations.CreateModel(
            name='HistorialPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ganados', 'Ganados'), ('canjeados', 'Canjeados'), ('expiraron', 'Expiraron'), ('ajuste', 'Ajuste Manual')], max_length=20)),
                ('puntos', models.IntegerField(help_text='Positivo=ganados, Negativo=canjeados')),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_puntos', to='core.barberia')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntos_generados', to='scheduling.cita')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_puntos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Puntos',
                'verbose_name_plural': 'Historial de Puntos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProgramaFidelidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_por_cita', models.PositiveIntegerField(default=10, help_text='Puntos ganados por cita completada')),
                ('pesos_por_punto', models.DecimalField(decimal_places=2, default=100, help_text='Valor en pesos de cada punto', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('minimo_canje', models.PositiveIntegerField(default=50, help_text='Mínimo de puntos para canjear')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('barberia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_fidelidad', to='core.barberia')),
            ],
            options={
                'verbose_name': 'Programa de Fidelidad',
                'verbose_name_plural': 'Programas de Fidelidad',
            },
        ),
    ]
