# Generated by Django 5.0.14 on 2025-11-23 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_puntos_fidelidad_historialpuntos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaExcepcional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('cerrado', 'Cerrado'), ('horario_especial', 'Horario Especial')], max_length=20)),
                ('hora_apertura', models.TimeField(blank=True, null=True)),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, help_text='Ej: Día festivo, evento privado', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_excepcionales', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Día Excepcional',
                'verbose_name_plural': 'Días Excepcionales',
                'db_table': 'bf_dias_excepcionales',
                'unique_together': {('sucursal', 'fecha')},
            },
        ),
    ]
