# Generated by Django 5.0.14 on 2025-11-24 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_diaexcepcional'),
        ('scheduling', '0008_cita_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('recordatorio_cita', 'Recordatorio de Cita'), ('confirmacion_cita', 'Confirmación de Cita'), ('cancelacion_cita', 'Cancelación de Cita'), ('cita_completada', 'Cita Completada'), ('promocion', 'Promoción')], default='recordatorio_cita', max_length=30)),
                ('asunto', models.CharField(max_length=200)),
                ('enviado_el', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, help_text='Mensaje de error si falla')),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to='scheduling.cita')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación Email',
                'verbose_name_plural': 'Notificaciones Email',
                'ordering': ['-enviado_el'],
                'indexes': [models.Index(fields=['destinatario', 'tipo', 'enviado_el'], name='core_notifi_destina_d2254e_idx'), models.Index(fields=['cita', 'tipo'], name='core_notifi_cita_id_208365_idx')],
            },
        ),
    ]
