# Generated by Django 5.0.14 on 2025-11-25 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente_puntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='barberia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='core.barberia'),
        ),
    ]
