# Generated by Django 5.0.14 on 2025-11-25 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_barberia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='barberia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.barberia'),
        ),
    ]
